name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to the Docker Hub
      run: echo $DOCKER_PASS | docker login --username foo --password-stdin
    - name: Push the Docker image
      run: docker push mrostanski/skrewdriver:$(date +%s)
