name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Login to the Docker Hub
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: docker login --username foo --password "$DOCKER_PASS"
      - name: Push the Docker image
        run: docker push mrostanski/skrewdriver:$(date +%s)
