name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx (Multiarch)
      - uses: docker/login-action@v2
        name: Login to DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Build & push Docker image
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$(basename ${{ github.repository }}):latest
